# version: '3'

# services:
#     db:
#       image: postgres
#     web:
#       build: .
#       command: python3 manage.py runserver 0.0.0.0:8000
#       volumes:
#         -   .:/src
#       ports:
#         -   "8000:8000"
#       depends_on:
#         -  db
#     node:
#       build: ../node-app
#       command: node node.js


version: '3'

services:
  db:
    image: postgres
  nodejs:
    build: ../node-app
    command: ./wait-for-it.sh http://web:8080 -- node node.js
    depends_on:
      - web
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/src
    ports:
      - "8000:8000"
    depends_on:
      - db